version: '3.8'
networks:
  ddi_chat_network:
    driver: bridge
volumes:
  ddi_chat_es_data:

services:
  vector_database:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: vector_database
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=$ES_PASSWORD
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ddi_chat_es_data:/usr/share/elasticsearch/data
    networks:
      - ddi_chat_network
