version: '3.8'
networks:
  ddi_chat_network:
    driver: bridge

services:
  proxy:
    image: nginx:latest
    container_name: server
    environment:
      TZ: Asia/Bangkok
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - ddi_chat_network
